from __future__ import annotations

"""
Schema-driven Skill architecture for domain knowledge extraction.

This module introduces a **Skill** abstraction that sits between high-level
orchestration and low-level tools:

    Schema (arbitrary JSON)
          ↓
    SkillSupervisor               (orchestrator — drives skill selection)
          ↓  activates
    Skills                        (parameterised, reusable extraction units)
          ↓  use internally
    Sub-Agents + Tools            (kb_query, write_json_file, …)
          ↓  write to
    tmp_dir/{key}.json            (scalar fields)
    tmp_dir/{key}/{item}.json     (list-category items)
          ↓
    MergeSkill                    (pure Python — combines all outputs)

Designed to run **alongside** the existing ProductInfoPipeline (pipeline.py).
The pipeline is specialised for the product schema; this module handles
arbitrary schemas via schema-driven skill decomposition.

Directory layout created by SkillSupervisor::

    {tmp_dir}/
      product.json             ← ScalarExtractSkill output
      components/              ← ListDiscoverSkill + ItemDetailSkill outputs
        body.json
        strap.json
        …
      features/
        spo2_monitoring.json
        …

Key design properties
---------------------
- **Parameterised**: each skill receives a schema_fragment at runtime.
- **Reusable**: the same ItemDetailSkill handles any list category.
- **Composable**: SkillSupervisor combines skills via a SkillPlan.
- **Reliable**: retry + text-based recovery (same pattern as pipeline.py).
- **Schema-agnostic**: supports any JSON schema, not just the product schema.
"""

import asyncio
import json
import logging
import re
import shutil
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Type

from langchain.agents import create_agent
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.tools import BaseTool

from agent.tools import build_rag_agent_tools, WriteJsonFileTool
from agent.util import get_last_ai_message_content
from agent.skill_prompt import (
    SKILL_SCALAR_EXTRACT_PROMPT,
    SKILL_LIST_DISCOVER_PROMPT,
    SKILL_ITEM_DETAIL_PROMPT,
)

logger = logging.getLogger(__name__)


# =============================================================================
# Runtime context & result
# =============================================================================

@dataclass
class SkillContext:
    """
    Runtime context injected into every skill at execution time.

    Holds all resources a skill needs (LLM, tools, paths) so that skills
    themselves remain stateless and reusable.
    """
    doc_meta: Dict[str, Any]
    schema: Dict[str, Any]          # full top-level schema (for MergeSkill)
    schema_fragment: Any            # slice of schema relevant to this skill
    target_key: str                 # e.g. "product", "components"
    tmp_dir: Path
    llm: BaseChatModel
    rag_tools: List[BaseTool]
    write_tool: WriteJsonFileTool
    max_retries: int = 2
    sub_agent_timeout: float = 180.0
    max_concurrency: int = 3


@dataclass
class SkillResult:
    """Unified return value from any skill execution."""
    success: bool
    output_path: Optional[Path] = None          # set by write-based skills
    discovered_items: Optional[List[str]] = None  # set by ListDiscoverSkill
    data: Optional[Any] = None                  # in-memory payload (e.g. MergeSkill)
    summary: str = ""


# =============================================================================
# Skill plan
# =============================================================================

@dataclass
class SkillStep:
    """Describes a single step in a SkillPlan."""
    skill_cls: Type[BaseSkill]
    target_key: str
    schema_fragment: Any

    def __repr__(self) -> str:
        return f"SkillStep({self.skill_cls.__name__}, key={self.target_key!r})"


@dataclass
class SkillPlan:
    """Ordered list of SkillSteps generated by SchemaAnalyzeSkill."""
    steps: List[SkillStep] = field(default_factory=list)

    def __repr__(self) -> str:
        lines = [f"SkillPlan ({len(self.steps)} steps):"]
        for i, s in enumerate(self.steps, 1):
            lines.append(f"  {i}. {s!r}")
        return "\n".join(lines)


# =============================================================================
# Abstract base
# =============================================================================

class BaseSkill(ABC):
    """
    Abstract base for all extraction skills.

    A Skill is a *parameterised, reusable* unit of extraction capability.
    It receives a SkillContext at runtime and returns a SkillResult.
    Skills are stateless — all mutable state lives in files on disk or
    in the SkillResult payload.
    """

    #: Short identifier used for logging and the SkillRegistry
    name: str = "base"
    #: Human-readable description (used in paper framing and diagnostics)
    description: str = ""

    @abstractmethod
    async def execute(self, ctx: SkillContext, **kwargs) -> SkillResult:
        """Execute the skill and return a SkillResult."""

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name={self.name!r})"


# =============================================================================
# SkillRegistry  — maps skill names to classes (useful for serialised plans)
# =============================================================================

class SkillRegistry:
    """
    Central registry that maps skill names to their implementation classes.

    Allows SkillPlan steps to be described by name in config files or logs
    and looked up at runtime.

    Usage::

        registry = SkillRegistry.default()
        cls = registry.get("item_detail")   # → ItemDetailSkill
    """

    def __init__(self) -> None:
        self._registry: Dict[str, Type[BaseSkill]] = {}

    def register(self, cls: Type[BaseSkill]) -> Type[BaseSkill]:
        """Register a skill class by its ``name`` attribute."""
        self._registry[cls.name] = cls
        return cls

    def get(self, name: str) -> Type[BaseSkill]:
        if name not in self._registry:
            raise KeyError(f"Unknown skill: {name!r}. Available: {list(self._registry)}")
        return self._registry[name]

    def all_names(self) -> List[str]:
        return list(self._registry.keys())

    @classmethod
    def default(cls) -> "SkillRegistry":
        """Return a pre-populated registry with all built-in skills."""
        reg = cls()
        for skill_cls in (
            SchemaAnalyzeSkill,
            ScalarExtractSkill,
            ListDiscoverSkill,
            ItemDetailSkill,
            MergeSkill,
        ):
            reg.register(skill_cls)
        return reg


# =============================================================================
# Skill 1 — SchemaAnalyzeSkill  (pure Python, no LLM)
# =============================================================================

class SchemaAnalyzeSkill(BaseSkill):
    """
    Analyse the schema structure and generate an ordered SkillPlan.

    Classification rules:
    - dict value   →  ScalarExtractSkill   (extract as a single JSON object)
    - list value   →  ListDiscoverSkill    (discover items, then ItemDetailSkill)

    Pure Python — no LLM call.  This is the entry point for every
    supervisor run.
    """

    name = "schema_analyze"
    description = (
        "Analyse the schema structure and generate an ordered skill execution plan. "
        "Determines which fields require scalar extraction vs. list discovery."
    )

    async def execute(self, ctx: SkillContext, **kwargs) -> SkillResult:
        schema = (
            ctx.schema_fragment
            if isinstance(ctx.schema_fragment, dict)
            else ctx.schema
        )
        steps: List[SkillStep] = []
        for key, value in schema.items():
            if isinstance(value, list):
                steps.append(SkillStep(
                    skill_cls=ListDiscoverSkill,
                    target_key=key,
                    schema_fragment=value,
                ))
            elif isinstance(value, dict):
                steps.append(SkillStep(
                    skill_cls=ScalarExtractSkill,
                    target_key=key,
                    schema_fragment=value,
                ))
            # Primitive / None values: no dedicated extraction step needed.

        plan = SkillPlan(steps=steps)
        logger.info("SchemaAnalyzeSkill generated:\n%s", plan)
        return SkillResult(success=True, data=plan, summary=repr(plan))


# =============================================================================
# Skill 2 — ScalarExtractSkill
# =============================================================================

class ScalarExtractSkill(BaseSkill):
    """
    Extract a scalar or dict-typed top-level schema field.

    Launches a focused sub-agent that queries the knowledge base and writes
    the result to ``{tmp_dir}/{target_key}.json`` via the write_json_file tool.
    """

    name = "scalar_extract"
    description = (
        "Extract a scalar or structured (dict) schema field from the knowledge base "
        "using a sub-agent. Writes the result to a JSON file."
    )

    async def execute(self, ctx: SkillContext, **kwargs) -> SkillResult:
        target_path = ctx.tmp_dir / f"{ctx.target_key}.json"
        schema_str = json.dumps(ctx.schema_fragment, ensure_ascii=False, indent=2)
        key_title = ctx.target_key.replace("_", " ").title()

        system_prompt = SKILL_SCALAR_EXTRACT_PROMPT.format(
            KEY_TITLE=key_title,
            TARGET_KEY=ctx.target_key,
            TARGET_FILE=str(target_path),
            SCHEMA_FRAGMENT=schema_str,
        )
        task = (
            f"Extract the '{ctx.target_key}' information from the knowledge base "
            f"and write it to: {target_path}"
        )
        tool_names = ["kb_query", "kb_chunk_query", "write_json_file"]
        tool_map = _build_tool_map(ctx)

        async def _do(attempt: int = 0) -> None:
            output = await _run_sub_agent(
                ctx.llm, tool_map,
                system_prompt, _strengthen(task, attempt),
                tool_names, ctx.sub_agent_timeout,
            )
            if not target_path.exists():
                _try_recover(output, target_path)
            if not target_path.exists():
                raise _FileNotWrittenError(target_path)

        try:
            await _with_retry(
                _do,
                label=f"scalar_extract/{ctx.target_key}",
                max_retries=ctx.max_retries,
            )
            return SkillResult(
                success=True,
                output_path=target_path,
                summary=f"Extracted '{ctx.target_key}' → {target_path.name}",
            )
        except Exception as exc:
            logger.error("ScalarExtractSkill failed for '%s': %s", ctx.target_key, exc)
            return SkillResult(success=False, summary=str(exc))


# =============================================================================
# Skill 3 — ListDiscoverSkill
# =============================================================================

class ListDiscoverSkill(BaseSkill):
    """
    Discover all item names within a list-typed schema field.

    Returns a SkillResult whose ``discovered_items`` contains the names;
    does NOT write anything to disk (that is left to ItemDetailSkill).
    The SkillSupervisor uses the discovered names to fan out ItemDetailSkill
    invocations in parallel.
    """

    name = "list_discover"
    description = (
        "Discover all item names in a list-type schema field using a sub-agent. "
        "Returns the list of names for downstream ItemDetailSkill invocations."
    )

    async def execute(self, ctx: SkillContext, **kwargs) -> SkillResult:
        # Use the first item template from the list as the schema example.
        item_template = (
            (ctx.schema_fragment or [{}])[0]
            if isinstance(ctx.schema_fragment, list)
            else {}
        )
        schema_str = json.dumps(item_template, ensure_ascii=False, indent=2)
        key_title = ctx.target_key.replace("_", " ").title()

        system_prompt = SKILL_LIST_DISCOVER_PROMPT.format(
            KEY_TITLE=key_title,
            TARGET_KEY=ctx.target_key,
            SCHEMA_FRAGMENT=schema_str,
        )
        task = (
            f"Identify all items in the '{ctx.target_key}' category from the "
            f"knowledge base. Return ONLY a JSON object: "
            f'{{"items": ["name1", "name2", ...]}}'
        )
        tool_names = ["kb_query", "kb_chunk_query"]
        tool_map = _build_tool_map(ctx)

        async def _do(attempt: int = 0) -> List[str]:
            output = await _run_sub_agent(
                ctx.llm, tool_map,
                system_prompt, task,
                tool_names, ctx.sub_agent_timeout,
            )
            items = _parse_items(output, ctx.target_key)
            if not items:
                raise ValueError(
                    f"Discovery returned zero items for '{ctx.target_key}'"
                )
            return items

        try:
            items = await _with_retry(
                _do,
                label=f"list_discover/{ctx.target_key}",
                max_retries=ctx.max_retries,
            )
            logger.info(
                "ListDiscoverSkill: found %d items in '%s': %s",
                len(items), ctx.target_key, items,
            )
            return SkillResult(
                success=True,
                discovered_items=items,
                summary=f"Discovered {len(items)} items in '{ctx.target_key}'",
            )
        except Exception as exc:
            logger.error("ListDiscoverSkill failed for '%s': %s", ctx.target_key, exc)
            return SkillResult(success=False, discovered_items=[], summary=str(exc))


# =============================================================================
# Skill 4 — ItemDetailSkill
# =============================================================================

class ItemDetailSkill(BaseSkill):
    """
    Extract detailed information for a single discovered item.

    Launched once per item by the SkillSupervisor (in parallel, bounded by
    a semaphore).  Writes result to
    ``{tmp_dir}/{target_key}/{item_name}.json``.

    Requires the keyword argument ``item_name`` at call time.
    """

    name = "item_detail"
    description = (
        "Extract detailed information for a specific list item from the knowledge base. "
        "Writes result to a JSON file inside the category subdirectory."
    )

    async def execute(self, ctx: SkillContext, *, item_name: str, **kwargs) -> SkillResult:
        cat_dir = ctx.tmp_dir / ctx.target_key
        cat_dir.mkdir(parents=True, exist_ok=True)
        target_path = cat_dir / _safe_filename(item_name)

        item_template = (
            (ctx.schema_fragment or [{}])[0]
            if isinstance(ctx.schema_fragment, list)
            else {}
        )
        schema_str = json.dumps(item_template, ensure_ascii=False, indent=2)
        key_title = ctx.target_key.replace("_", " ").title()

        system_prompt = SKILL_ITEM_DETAIL_PROMPT.format(
            KEY_TITLE=key_title,
            TARGET_KEY=ctx.target_key,
            ITEM_NAME=item_name,
            TARGET_FILE=str(target_path),
            SCHEMA_FRAGMENT=schema_str,
        )
        task = (
            f"Extract detailed information for '{ctx.target_key}' item '{item_name}' "
            f"and write it to: {target_path}"
        )
        tool_names = [
            "kb_query", "kb_chunk_query", "kb_page_context", "write_json_file",
        ]
        tool_map = _build_tool_map(ctx)

        async def _do(attempt: int = 0) -> None:
            output = await _run_sub_agent(
                ctx.llm, tool_map,
                system_prompt, _strengthen(task, attempt),
                tool_names, ctx.sub_agent_timeout,
            )
            if not target_path.exists():
                _try_recover(output, target_path)
            if not target_path.exists():
                raise _FileNotWrittenError(target_path)

        try:
            await _with_retry(
                _do,
                label=f"item_detail/{ctx.target_key}/{item_name}",
                max_retries=ctx.max_retries,
            )
            return SkillResult(
                success=True,
                output_path=target_path,
                summary=f"Extracted '{ctx.target_key}/{item_name}'",
            )
        except Exception as exc:
            logger.error(
                "ItemDetailSkill failed for '%s/%s': %s",
                ctx.target_key, item_name, exc,
            )
            return SkillResult(success=False, summary=str(exc))


# =============================================================================
# Skill 5 — MergeSkill  (pure Python, no LLM)
# =============================================================================

class MergeSkill(BaseSkill):
    """
    Merge all JSON files written by extraction skills into a final result dict.

    Merge rules (schema-driven):
    - ``{tmp_dir}/{key}.json``       →  result[key] = dict
    - ``{tmp_dir}/{key}/``           →  result[key] = [list of dicts]

    Pure Python — no LLM call.  This is always the final step.
    """

    name = "merge"
    description = (
        "Merge all extraction outputs into a single structured result dict. "
        "Scalar JSON files become dict values; category directories become lists."
    )

    async def execute(self, ctx: SkillContext, **kwargs) -> SkillResult:
        result: Dict[str, Any] = {}

        for key in ctx.schema.keys():
            scalar_path = ctx.tmp_dir / f"{key}.json"
            cat_dir = ctx.tmp_dir / key

            if scalar_path.exists():
                try:
                    result[key] = json.loads(
                        scalar_path.read_text(encoding="utf-8")
                    )
                except (json.JSONDecodeError, OSError) as exc:
                    logger.warning("MergeSkill: failed to read %s: %s", scalar_path, exc)

            elif cat_dir.is_dir():
                items: List[Dict[str, Any]] = []
                for f in sorted(cat_dir.glob("*.json")):
                    try:
                        obj = json.loads(f.read_text(encoding="utf-8"))
                        if isinstance(obj, dict):
                            items.append(obj)
                        elif isinstance(obj, list):
                            items.extend(x for x in obj if isinstance(x, dict))
                    except (json.JSONDecodeError, OSError) as exc:
                        logger.warning("MergeSkill: failed to read %s: %s", f, exc)
                if items:
                    result[key] = items

        logger.info("MergeSkill: merged keys=%s", list(result.keys()))
        return SkillResult(
            success=True,
            data=result,
            summary=f"Merged {len(result)} top-level keys: {list(result.keys())}",
        )


# =============================================================================
# SkillSupervisor
# =============================================================================

class SkillSupervisor:
    """
    Schema-driven supervisor that orchestrates extraction skills.

    Workflow::

        1. SchemaAnalyzeSkill  →  parse schema, generate SkillPlan
        2. For each SkillStep in plan:
              ScalarExtractSkill  →  extract dict-typed fields
              ListDiscoverSkill   →  discover item names in list fields
                └─ ItemDetailSkill (×N, parallel)  →  extract each item
        3. MergeSkill           →  combine all JSON files into final result

    Unlike the ProductInfoPipeline which hard-codes the product schema steps,
    SkillSupervisor works with **any** JSON schema by deriving the execution
    plan at runtime via SchemaAnalyzeSkill.

    Usage::

        supervisor = SkillSupervisor(doc_meta, schema, llm)
        result = await supervisor.run()
        supervisor.cleanup()
    """

    def __init__(
        self,
        doc_meta: Dict[str, Any],
        schema: Dict[str, Any],
        llm: BaseChatModel,
        *,
        max_retries: int = 2,
        sub_agent_timeout: float = 180.0,
        max_concurrency: int = 3,
        verbose: bool = False,
    ) -> None:
        self.doc_meta = doc_meta
        self.schema = schema
        self.llm = llm
        self.max_retries = max_retries
        self.sub_agent_timeout = sub_agent_timeout
        self.max_concurrency = max_concurrency
        self.verbose = verbose

        # Isolated tmp directory for this supervisor run.
        runtime_root = Path(doc_meta.get("working_dir", ".")).resolve().parent
        self._tmp_dir = runtime_root / "skill_tmp"
        if self._tmp_dir.exists():
            shutil.rmtree(self._tmp_dir, ignore_errors=True)
        self._tmp_dir.mkdir(parents=True, exist_ok=True)
        logger.info("SkillSupervisor tmp_dir: %s", self._tmp_dir)

        self._rag_tools = build_rag_agent_tools(doc_meta)
        self._write_tool = WriteJsonFileTool(
            allowed_directory=str(self._tmp_dir)
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def run(self) -> Dict[str, Any]:
        """Execute the full skill pipeline and return the merged result."""
        t0 = time.perf_counter()

        # Step 1 — Schema analysis (pure Python, no LLM)
        plan_result = await SchemaAnalyzeSkill().execute(
            self._make_ctx("__schema__", self.schema)
        )
        plan: SkillPlan = plan_result.data

        # Step 2 — Execute each planned step
        for step in plan.steps:
            ctx = self._make_ctx(step.target_key, step.schema_fragment)

            if step.skill_cls is ScalarExtractSkill:
                await ScalarExtractSkill().execute(ctx)

            elif step.skill_cls is ListDiscoverSkill:
                discover_result = await ListDiscoverSkill().execute(ctx)
                items = discover_result.discovered_items or []
                if items:
                    await self._run_item_detail_parallel(ctx, items)

        # Step 3 — Merge (pure Python, no LLM)
        merge_result = await MergeSkill().execute(
            self._make_ctx("__merge__", self.schema)
        )
        result: Dict[str, Any] = merge_result.data or {}

        elapsed = time.perf_counter() - t0
        logger.info(
            "SkillSupervisor finished in %.1fs  keys=%s  tmp_dir=%s",
            elapsed, list(result.keys()), self._tmp_dir,
        )
        return result

    def cleanup(self) -> None:
        """Remove the tmp directory. Call after you are done with the result."""
        if self._tmp_dir.exists():
            shutil.rmtree(self._tmp_dir, ignore_errors=True)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _make_ctx(self, target_key: str, schema_fragment: Any) -> SkillContext:
        return SkillContext(
            doc_meta=self.doc_meta,
            schema=self.schema,
            schema_fragment=schema_fragment,
            target_key=target_key,
            tmp_dir=self._tmp_dir,
            llm=self.llm,
            rag_tools=self._rag_tools,
            write_tool=self._write_tool,
            max_retries=self.max_retries,
            sub_agent_timeout=self.sub_agent_timeout,
            max_concurrency=self.max_concurrency,
        )

    async def _run_item_detail_parallel(
        self, ctx: SkillContext, item_names: List[str]
    ) -> None:
        """Fan out ItemDetailSkill for every discovered item, bounded by semaphore."""
        sem = asyncio.Semaphore(self.max_concurrency)

        async def _one(name: str) -> None:
            async with sem:
                await ItemDetailSkill().execute(ctx, item_name=name)

        results = await asyncio.gather(
            *[_one(n) for n in item_names],
            return_exceptions=True,
        )
        for name, res in zip(item_names, results):
            if isinstance(res, Exception):
                logger.error(
                    "ItemDetailSkill failed for '%s/%s': %s",
                    ctx.target_key, name, res,
                )


# =============================================================================
# Private utilities (shared by LLM-backed skills)
# =============================================================================

def _safe_filename(name: str) -> str:
    """Turn an arbitrary item name into a safe JSON file stem."""
    stem = re.sub(r"[^\w\-]", "_", name.strip())[:120]
    return (stem or "unnamed") + ".json"


def _build_tool_map(ctx: SkillContext) -> Dict[str, BaseTool]:
    all_tools = ctx.rag_tools + [ctx.write_tool]
    return {t.name: t for t in all_tools}


async def _run_sub_agent(
    llm: BaseChatModel,
    tool_map: Dict[str, BaseTool],
    system_prompt: str,
    task: str,
    tool_names: List[str],
    timeout: float = 180.0,
) -> str:
    """Spin up a fresh sub-agent, run it with a timeout, and return text output."""
    tools = [tool_map[n] for n in tool_names if n in tool_map]
    if not tools:
        raise ValueError(f"No valid tools found for names: {tool_names}")

    agent = create_agent(model=llm, tools=tools, system_prompt=system_prompt)
    messages = [{"role": "user", "content": task}]
    config = {"max_concurrency": 3, "recursion_limit": 50}

    coro = asyncio.to_thread(agent.invoke, {"messages": messages}, config=config)
    result = await asyncio.wait_for(coro, timeout=timeout)

    text = get_last_ai_message_content(result)
    return text or str(result)


async def _with_retry(fn, *, label: str = "", max_retries: int = 2) -> Any:
    """Call ``fn(attempt=N)`` with exponential-backoff retry."""
    last_exc: Optional[Exception] = None
    for attempt in range(max_retries + 1):
        try:
            return await fn(attempt=attempt)
        except Exception as exc:
            last_exc = exc
            if attempt < max_retries:
                wait = min(2 ** attempt * 2, 30)
                logger.warning(
                    "[%s] attempt %d/%d failed (%s). Retrying in %ds …",
                    label, attempt + 1, max_retries + 1, exc, wait,
                )
                await asyncio.sleep(wait)
    raise last_exc  # type: ignore[misc]


def _strengthen(task: str, attempt: int) -> str:
    """Prepend a stronger directive on retry attempts."""
    if attempt == 0:
        return task
    return (
        "CRITICAL: Your previous attempt FAILED because you did NOT call "
        "the write_json_file tool. You MUST call it this time to write "
        "the result to the specified file path.\n\n" + task
    )


def _try_recover(text: str, target_path: Path) -> bool:
    """
    If the sub-agent returned JSON in its text reply instead of calling
    write_json_file, extract the JSON and write the file ourselves.
    """
    obj = _try_parse_json_object(text)
    if obj is None:
        return False
    try:
        target_path.parent.mkdir(parents=True, exist_ok=True)
        target_path.write_text(
            json.dumps(obj, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
        logger.info("Recovered JSON from agent text → %s", target_path)
        return True
    except OSError as exc:
        logger.warning("Recovery write failed for %s: %s", target_path, exc)
        return False


def _try_parse_json_object(text: str) -> Optional[Dict[str, Any]]:
    """Find the first balanced ``{...}`` JSON object in text (handles code fences)."""
    if not text:
        return None
    cleaned = re.sub(r"```(?:json)?\s*", "", text)
    cleaned = re.sub(r"```", "", cleaned)

    brace_depth = 0
    start: Optional[int] = None
    for i, ch in enumerate(cleaned):
        if ch == "{":
            if brace_depth == 0:
                start = i
            brace_depth += 1
        elif ch == "}":
            brace_depth -= 1
            if brace_depth == 0 and start is not None:
                candidate = cleaned[start : i + 1]
                try:
                    obj = json.loads(candidate)
                    if isinstance(obj, dict):
                        return obj
                except json.JSONDecodeError:
                    pass
                start = None
    return None


def _parse_items(text: str, category: str) -> List[str]:
    """Best-effort extraction of an item list from a sub-agent text response."""
    if not text:
        return []

    for key in ("items", category):
        pattern = r'\{\s*"' + re.escape(key) + r'"\s*:\s*(\[.*?\])\s*\}'
        m = re.search(pattern, text, re.DOTALL)
        if m:
            try:
                arr = json.loads(m.group(1))
                return [str(x).strip() for x in arr if str(x).strip()]
            except json.JSONDecodeError:
                pass

    m = re.search(r"\[.*?\]", text, re.DOTALL)
    if m:
        try:
            arr = json.loads(m.group())
            if arr and all(isinstance(x, str) for x in arr):
                return [x.strip() for x in arr if x.strip()]
        except json.JSONDecodeError:
            pass

    bullets = re.findall(r"(?:^|\n)\s*(?:[-*]|\d+\.)\s+(.+)", text)
    if bullets:
        return [b.strip().strip('"').strip("'") for b in bullets if b.strip()]

    return []


class _FileNotWrittenError(RuntimeError):
    """Raised when a sub-agent finishes without writing the expected file."""
    def __init__(self, path: Path) -> None:
        super().__init__(
            f"Expected file was not created: {path}. "
            "The agent may have returned JSON in text instead of calling write_json_file."
        )
